import { Buffer } from 'buffer';
import { JobState } from './enums';
import AttemptError from './error';
import JobArgs from './job-args';
/**
 * Represents a job persisted in the database, including its state, metadata, and scheduling information.
 */
export default interface Job<T extends JobArgs = JobArgs> {
  /** Unique job ID, generated by the database */
  id: number;
  /** Current state of the job (e.g., available, completed) */
  state: JobState;
  /** Current attempt number, incremented each time the job is worked */
  attempt: number;
  /** Maximum number of attempts before the job stops retrying */
  maxAttempts: number;
  /** Last time the job was worked, null if never */
  attemptedAt: Date | null;
  /** When the job record was created */
  createdAt: Date;
  /** When the job was finalized (completed or errored for last time), null if not finalized */
  finalizedAt: Date | null;
  /** When the job is scheduled to become available */
  scheduledAt: Date;
  /** Job priority (1 = highest, 4 = lowest) */
  priority: number;
  /** Job arguments, decoded from JSON */
  args: T;
  /** Worker IDs that have worked this job, null if never */
  attemptedBy: string[] | null;
  /** Errors for each attempt, ordered earliest to latest, null if none */
  errors: AttemptError[] | null;
  /** Job type identifier, set at insertion */
  kind: string;
  /** Arbitrary metadata associated with the job */
  metadata: Record<string, unknown>;
  /** Name of the queue where the job will be worked */
  queue: string;
  /** List of tags for grouping and categorizing jobs */
  tags: string[];
  /** Unique key for job within its kind, used for unique insertions, null if not set */
  uniqueKey: Buffer | null;
  /** States required for uniqueness, null if not set */
  uniqueStates: JobState[] | null;
}
